/* Map facade. Every area's grid and spawn point are generated by
   tools/build_map.py into mapdata.js; this adds what the game asks of them.

   One map per area, switched from the MAP tab - not one continuous world. A
   world needs transition tiles between biomes, and without them every zone is a
   hard rectangle butted against grass.

   Legend: . grass · , tall grass · f flowers · # sand path · T tree
           w pond water (solid) · b its shore, the water's bottom edge
           L ledge (solid; walking south hops it) · J one you hop EAST
           F forest canopy
           c canopy overhang (walkable - you pass behind the tree top)
           D wooden pier (walkable) · o cave floor crater (2x2)
           r cave floor · R cave wall · u cave plateau (the upper level)
           C cliff face below a plateau (solid) · S stairs up it
           W cave pool, 2x2 in a rock face (solid, fishable)
           p power-plant floor · P machine bank (3 rows) · X console in a bank
           B barrels hung off a bank's foot · E the room's outer wall
           Y a partition standing on end, hung from a wall
           m volcano floor · M volcanic rock, and the bank around a pool
           V lava (solid) · l ladder · n plank bridge over lava
           i lower ice · j raised ice shelf · I ice wall · d ice boulder
           t stalactite (2x2, in the ceiling)
           k water (solid) · K waterfall · s stairs between the two ice levels
           n bridge over lava · N bridge over water
           q mansion floor · Q its wall - Cinnabar's burnt-out house
           h tower floor · H tower wall · G a grave standing on the floor
           A a grave set into the wall · y the ward (3x3, walkable)
           Z solid scenery a COPIED map brought with it - Route 1's white
             fence and its signpost. It has no shape rule and needs none: a
             transcribed cell draws with the real map's own metatile, so the
             character only has to be right about collision.
           p/P plant
   Lowercase is walkable ground, uppercase the solid wall of the same biome. */

import { AREAS, AREA_IDS } from "./mapdata.js";

export { AREAS, AREA_IDS };

// A ledge is solid to ordinary movement; the engine handles the hop.
export const SOLID = "T~wRMIPHLFCWXBEVkKdtYGAZJQ";

/* A LEDGE IS ONE-WAY, AND WHICH WAY IS THE CHARACTER'S: the value is the step
   that hops it, so `L` is hopped by walking south and `J` by walking east.

   `L` was the only one there was, and the reason is that every map we DREW put
   its terraces above the path - south is the only direction a ledge ever
   needed to face. Route 112 is a MOUNTAINSIDE, and 38 of its 41 ledges face
   east, drawn as vertical strips down the slope. With one direction available
   they had to be laid as floor, which is walkable both ways - a ledge you can
   climb back up, which is not a ledge. Reported from play.

   A table rather than a second special case in `tryStep`, because west and
   north are then one row each instead of another branch, and because
   tools/build_map.py needs the identical answer: `walk_steps` is the one
   definition of a step and a directed fill that disagreed with the engine
   would pass a map that traps the player on a terrace. check.mjs holds the two
   copies together, exactly as it does for `SOLID`. */
export const LEDGE = { L: [0, 1], J: [1, 0] };

/* WHAT YOU CAN RIDE, and it is a subset of SOLID rather than a new kind of
   ground: every one of these is impassable on foot and stays so. `w` is open
   water, `W` the Rock Ridge spring, `k` the pools in Frost Hollow - the same
   three a rod reaches, and for the same reason, which is that they are the same
   water. `V` is lava, which nothing in any Pokemon game has ever let you ride
   and which this game's own Ember Caldera is two thirds made of.

   `K` is out, exactly as it is for fishing: that is the waterfall, and it is
   falling. `~` is out because it is the out-of-bounds border, not a place. */
export const SURFABLE = "wWkV";
export const rideable = (rows, x, y) =>
  y >= 0 && y < rows.length && x >= 0 && x < rows[y].length
  && SURFABLE.includes(rows[y][x]);

/* The minimap's palette, one colour per legend character.

   It lives here rather than with the renderer because it IS the legend - the
   same table that says `V` is lava says lava is orange - and a second list of
   characters somewhere else is how a new tile ends up drawn as "unknown grey"
   on the minimap and nobody notices for a month.

   Three rules held it together. **Walkable reads lighter than its own wall**,
   in every biome, so the shape of a route is legible with no key to consult:
   that is the only thing a 3px-per-tile picture can actually communicate. And
   **water is blue everywhere** - the pond, the cave spring, the ice lake - so
   the one feature a player navigates by does not change colour per area.

   Third, and it is the one the first draft got wrong: **two walkable levels
   have to be told apart.** Rock Ridge's plateau and Frost Hollow's raised
   shelf are not reachable from the floor beside them except at one staircase,
   so a minimap that paints them a shade apart from their own floor is showing
   a route that is not there - which is worse than showing nothing. `u` against
   `r`, and `j` against `i`, are deliberately further apart than they look like
   they need to be. */
export const MINI = {
  // route
  ".": "#6fae56", ",": "#54924a", f: "#7fbb63", "#": "#ded0a4",
  w: "#4b7fc4", b: "#c6b988", T: "#2d6634", F: "#26582b", c: "#3d7742",
  L: "#8a6a3c", J: "#8a6a3c", D: "#9a6a3a", N: "#9a6a3a", "~": "#4b7fc4",
  /* Route 1's fence and signpost. DARK, although the fence is painted white in
     the game: at 3px a tile the only thing this palette can say is walkable or
     not, and a light bar across the foot of the map would read as the path it
     blocks. */
  Z: "#6b6478",
  // cave
  r: "#9d9289", o: "#8b8078", R: "#4a423d", u: "#d3c2a2", C: "#5d534c",
  S: "#dcd0ba", W: "#4b7fc4",
  // power plant
  p: "#8e9298", P: "#54585e", X: "#3d6f8c", B: "#6b4f34", E: "#2f3237",
  Y: "#4a4e54",
  // ember caldera
  m: "#8a5a44", M: "#472d26", V: "#e2622a", l: "#c9a35e", n: "#9a6a3a",
  // frost hollow
  i: "#a9cde4", j: "#eef7fc", I: "#5d84a1", d: "#89a9bf", t: "#7396ad",
  k: "#4b7fc4", K: "#a9cfe8", s: "#dcd0ba",
  // haunted tower
  h: "#6b5f7a", H: "#2a2333", G: "#9a92a8", A: "#8a82a0", y: "#4fd2d2",
  /* pokemon mansion - scorched parquet against charred wall. Four floors on
     one grid, so the contrast has to carry the room shapes at 3px a tile with
     no other cue: this is the widest walkable-against-wall gap in the table. */
  q: "#b99763", Q: "#3b2a24",
};
/* Anything the legend grows without telling this table. Deliberately a colour
   nothing else uses, so a missing tile shows up as a magenta stripe rather
   than blending into the floor. */
export const MINI_UNKNOWN = "#ff00d0";

export const areaOf = (id) => AREAS[id] ?? AREAS[AREA_IDS[0]];

export const walkable = (rows, x, y) =>
  y >= 0 && y < rows.length && x >= 0 && x < rows[0].length &&
  !SOLID.includes(rows[y][x]);

const NAME_FIX = {
  "nidoran-f": "Nidoran\u2640", "nidoran-m": "Nidoran\u2642",
  "mr-mime": "Mr. Mime", farfetchd: "Farfetch'd",
};
const cap = (w) => w[0].toUpperCase() + w.slice(1);

/* A FORM IS NAMED THE WAY THE GAMES NAME IT, not the way PokeAPI keys it.
   Its `name` is a slug - "charizard-mega-x", "venusaur-gmax" - and title-casing
   that gives "Charizard-mega-x", which is a database row rather than a
   Pokemon. The prefix goes in front and the X/Y stays behind, because that is
   what Mega Charizard X is called. Driven off the `form` field rather than off
   the string, so a species that simply has a hyphen in its real name (tapu-koko,
   mr-mime) is untouched. */
const FORM_WORD = { mega: "Mega", primal: "Primal", gmax: "Gigantamax" };

export const label = (s) => {
  if (s.form) {
    const base = s.name.replace(/-(mega|primal|gmax|eternamax)(-[xy])?$/, "");
    const tail = s.name.match(/-(x|y)$/)?.[1];
    const name = NAME_FIX[base] ?? cap(base);
    return `${FORM_WORD[s.form] ?? cap(s.form)} ${name}${tail ? ` ${tail.toUpperCase()}` : ""}`;
  }
  return NAME_FIX[s.name] ?? cap(s.name);
};
