/* npm run edge — bundle the referee for the ranked-step Edge Function.

   A deployed function cannot reach src/, so src/game/referee.js and all it
   imports (battle.js, the moves, learnsets and species) are bundled into
   supabase/functions/ranked-step/rules.js, a GENERATED file: never edited by
   hand, re-made by this command, and compared byte for byte by check.mjs
   (which bundles in memory the same way), so a rules change that was not
   re-bundled fails the suite instead of reaching the server stale. */
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";

export const HEADER = "// Generated by tools/build-edge.mjs from src/game/referee.js - do not edit. docs/ranked.md, 6b.\n";
export const RULES = new URL("../supabase/functions/ranked-step/rules.js", import.meta.url);

export async function bundle() {
  const out = await build({
    entryPoints: [fileURLToPath(new URL("../src/game/referee.js", import.meta.url))],
    bundle: true, format: "esm", platform: "neutral", minify: true, legalComments: "none",
    write: false, logLevel: "silent",
  });
  return HEADER + out.outputFiles[0].text;
}

// Run as a command (not imported by check.mjs, or from an eval with no script path).
if (process.argv[1] && fileURLToPath(import.meta.url) === resolve(process.argv[1])) {
  const text = await bundle();
  writeFileSync(RULES, text);
  console.log(`  rules.js: ${Math.round(text.length / 1024)} KB`);
}
