"""The card back and each set's real booster wrappers, from Bulbagarden
Archives (docs/cards.md, Art). Run by `npm run cards` after fetch-cards.mjs.

Writes:
  public/cards/back.webp                 the real Pokémon TCG card back
  public/cards/<set>/pack-<slug>.webp    each wrapper the set was printed in
  src/data/cards/art.js                  which wrappers each set has - read by
                                         the lazy Cards page only

A set prints several wrappers (Mega Evolution: Venusaur, Gardevoir, Lucario,
Kangaskhan); which one a pack opens in is cosmetic and chosen by the page -
it changes no roll. Originals are cached in .assets-src/bulba/."""
import io
import json
import os
import re
import urllib.parse
import urllib.request

from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CACHE = os.path.join(ROOT, ".assets-src", "bulba")
API = "https://archives.bulbagarden.net/w/api.php"
UA = {"User-Agent": "Dexora (non-commercial fan game; build-time asset fetch)"}
BACK = "Cardback.jpg"
WRAPPERS = {
    "me01": ["ME1 Booster Mega Venusaur.png", "ME1 Booster Mega Gardevoir.png",
             "ME1 Booster Mega Lucario.png", "ME1 Booster Mega Kangaskhan.png"],
    "me02": ["ME2 Booster Mega Charizard X.png", "ME2 Booster Mega Gengar.png",
             "ME2 Booster Mega Heracross.png", "ME2 Booster Mega Lopunny.png"],
    "me02.5": ["Ascended Heroes Booster.png"],
    "sv03.5": ["151 Booster.png"],
    "sv08.5": ["Prismatic Evolutions Booster Eevee Sylveon.png", "Prismatic Evolutions Booster Espeon Umbreon.png",
               "Prismatic Evolutions Booster Leafeon Glaceon.png",
               "Prismatic Evolutions Booster Vaporeon Jolteon Flareon.png"],
    "me03": ["ME3 Booster Mega Zygarde.png", "ME3 Booster Mega Clefable.png", "ME3 Booster Mega Starmie.png",
             "ME3 Booster Meowth.png"],
    "me04": ["ME4 Booster Mega Greninja.png", "ME4 Booster Mega Floette.png", "ME4 Booster Mega Dragalge.png",
             "ME4 Booster Mega Pyroar.png"],
    "me05": ["ME5 Booster Mega Darkrai.png", "ME5 Booster Mega Zeraora.png", "ME5 Booster Mega Chandelure.png",
             "ME5 Booster Mega Excadrill.png"],
    "30th": ["30th Celebration Booster.png"],
}
# A set TCGdex has no logo for gets one from here (fetch-cards leaves it out).
LOGOS = {"30th": "30th Anniversary logo.png"}
LOGO_W = 400
PACK_W = 300          # shown at most ~230px wide, twice that on a dense screen is wasted here
BACK_W = 490


def get(url):
    with urllib.request.urlopen(urllib.request.Request(url, headers=UA), timeout=60) as r:
        return r.read()


def original(name):
    os.makedirs(CACHE, exist_ok=True)
    path = os.path.join(CACHE, name.replace(" ", "_"))
    if not os.path.exists(path):
        q = urllib.parse.urlencode({"action": "query", "titles": "File:" + name, "prop": "imageinfo",
                                    "iiprop": "url", "format": "json"})
        page = next(iter(json.loads(get(f"{API}?{q}"))["query"]["pages"].values()))
        if "imageinfo" not in page:
            raise SystemExit(f"Bulbagarden has no {name}")
        open(path, "wb").write(get(page["imageinfo"][0]["url"]))
    return Image.open(path)


def save(img, width, out):
    img = img.convert("RGBA")
    img = img.resize((width, round(img.height * width / img.width)), Image.LANCZOS)
    img.save(out, "WEBP", quality=86, method=6)
    return os.path.getsize(out)


def main():
    index = open(os.path.join(ROOT, "src", "data", "cards", "index.js"), encoding="utf-8").read()
    shipped = json.loads(re.search(r"CARD_SETS = (\[.*\]);", index).group(1))
    os.makedirs(os.path.join(ROOT, "public", "cards"), exist_ok=True)
    print("back.webp", save(original(BACK), BACK_W, os.path.join(ROOT, "public", "cards", "back.webp")), "bytes")
    art = {}
    for s in shipped:
        names = WRAPPERS.get(s["id"])
        if not names:
            raise SystemExit(f"{s['id']} has no wrapper art listed - add it to WRAPPERS")
        if s["id"] in LOGOS:
            print(s["id"], "logo.webp", save(original(LOGOS[s["id"]]), LOGO_W, os.path.join(ROOT, "public", "cards", s["id"], "logo.webp")), "bytes")
        art[s["id"]] = []
        for name in names:
            slug = re.sub(r"[^a-z0-9]+", "-", name.lower().rsplit(".", 1)[0].split("booster", 1)[-1]).strip("-") or "pack"
            out = os.path.join(ROOT, "public", "cards", s["id"], f"pack-{slug}.webp")
            print(s["id"], slug, save(original(name), PACK_W, out), "bytes")
            art[s["id"]].append(slug)
    with open(os.path.join(ROOT, "src", "data", "cards", "art.js"), "w", encoding="utf-8", newline="\r\n") as f:
        f.write("/* GENERATED by tools/fetch_card_art.py (npm run cards) - each set's booster\n"
                "   wrappers (public/cards/<set>/pack-<slug>.webp). Cosmetic: no roll reads it. */\n"
                f"export const WRAPPERS = {json.dumps(art)};\n")


if __name__ == "__main__":
    main()
