/* npm run anchors — the League's anchors on the ranked ladder (docs/ranked.md, 6c).

   Every region's Elite Four and Champion stands in the ladder as a CPU
   trainer at a FIXED rating, so there is always somebody to meet and ratings
   cannot drift while few people play. They play the ranked format: their
   species at Lv 100 with level-up moves (not their game movesets - the format
   is species alone), one of each species.

   Each rating is SOLVED, never typed: the anchor's win rate against random
   legal teams drawn from the whole dex (AI 3 against AI 3, on a fixed record)
   is turned into the Elo rating that win rate means against a field rated
   1000 - a random collection is the 1000 of this ladder. Writes
   src/data/anchors.js (generated); check.mjs replays the record exactly. */
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { LEAGUES } from "../src/data/leagues.js";
import { SPECIES } from "../src/data/dex.js";
import { rankedFighter, simulate, mulberry32 } from "../src/game/battle.js";
import { teamProblem, baseOf } from "../src/game/ranked.js";

export const ANCHOR_RECORD = { n: 200, seed: 17 };
// The widest an anchor may sit from 1000: a win rate of 99% or 1% says "far",
// not how far, and an anchor out there would never be anybody's match.
export const ANCHOR_SPREAD = 600;
const TEAM = 6;

// The field: every species a player could own (the whole dex, forms included).
const FIELD = SPECIES.filter((sp) => sp.stats.reduce((a, b) => a + b, 0) >= 180).map((sp) => sp.id);

// One of each species, in party order, as the format allows.
function formatTeam(party) {
  const seen = new Set(), team = [];
  for (const [id] of party) {
    if (seen.has(baseOf(id))) continue;
    seen.add(baseOf(id));
    team.push(id);
  }
  return team;
}
function randomTeam(rng) {
  const seen = new Set(), team = [];
  while (team.length < TEAM) {
    const id = FIELD[Math.floor(rng() * FIELD.length)];
    if (seen.has(baseOf(id))) continue;
    seen.add(baseOf(id));
    team.push(id);
  }
  return team;
}

export function solveAnchors({ n, seed } = ANCHOR_RECORD) {
  const out = [];
  for (const r of LEAGUES) {
    for (const p of r.league) {
      const team = formatTeam(p.party);
      if (teamProblem(team)) throw new Error(`${p.id}'s team is not legal in the format: ${teamProblem(team)}`);
      let wins = 0;
      for (let i = 0; i < n; i++) {
        const rng = mulberry32(seed * 7919 + i * 104729);
        const field = randomTeam(rng).map((id, k) => rankedFighter(id, k + 1));
        const mine = team.map((id, k) => rankedFighter(id, 100 + k));
        wins += simulate(field, mine, 3, 3, rng).over === 1;
      }
      // Laplace: never exactly 0 or 1, which have no finite rating.
      const w = (wins + 0.5) / (n + 1);
      const rating = Math.round(1000 + Math.max(-ANCHOR_SPREAD, Math.min(ANCHOR_SPREAD, 400 * Math.log10(w / (1 - w)))));
      out.push({ id: p.id, name: `${p.cls || (p.champion ? "Champion" : "Elite Four")} ${p.name}`, pic: p.pic, team, rating, win: w });
    }
  }
  return out;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === resolve(process.argv[1])) {
  const t0 = Date.now();
  const anchors = solveAnchors();
  const rows = anchors.map((a) => `  ${JSON.stringify(a)}`).join(",\n");
  writeFileSync(new URL("../src/data/anchors.js", import.meta.url),
    "// Generated by tools/rank-anchors.mjs - do not edit by hand. docs/ranked.md, 6c.\n" +
    `export const ANCHORS = [\n${rows}\n];\n`);
  const r = anchors.map((a) => a.rating).sort((x, y) => x - y);
  console.log(`  ${anchors.length} anchors, ratings ${r[0]}-${r.at(-1)} (median ${r[r.length >> 1]}), ${Math.round((Date.now() - t0) / 1000)}s`);
}
