/* node tools/tune-gyms.mjs [--trainers] — solve the League's levels, and price them.

   Writes src/data/gymtune.js (generated; its own file, because a generated
   file with two writers is a trap - leagues.js is fetch-leagues'):

     SHARE          the candy share the ladder is built on (solved: the last
                    Champion asks for a Lv 100 team as a playthrough ends)
     GYM_PRIZE      encounters of income a first win pays (solved from PRIZE_CEIL)
     REMATCH_STEPS  a leader's rematch clock (solved from REMATCH_CEIL)
     GYMTUNE        per capped opponent: its intended trainer level T, its cap,
                    its solved `top` (ace level, past 100 training), the win
                    rate on the RECORD, and its first-win prize
     TRAINERTUNE    per gym trainer: its level (its leader's, in proportion,
                    lowered only to clear TRAINER_FLOOR) and its win rate
     HARD_PRIZE, HARD_FEE, HARDTUNE   hard mode (phase 8): per capped
                    opponent's `<id>:hard`, its region, role and place, its
                    solved training (`top`, 100 + effort), the win rate on
                    HARD_RECORD, and the signature Pokemon a first win gives

   Every level is SOLVED, never typed (tools/league-sim.mjs). check.mjs
   re-derives the ladder and the prices exactly and replays every recorded
   battle, so a change to the rules, the rosters or the economy fails there
   and says to run this again. `--trainers` re-solves only the gym trainers
   against the leaders already solved (the leaders take ~18 minutes);
   `--hard` only hard mode (~20 minutes), keeping everything else.
   docs/battles.md, *Difficulty*. */

import { writeFileSync } from "node:fs";
import {
  ladder, solve, solveTrainer, trainerTop, prices, hardRungs, solveHard, hardPrices, signature, HARD_TARGET,
} from "./league-sim.mjs";

const { share, rungs } = ladder();
const hardOnly = process.argv.includes("--hard");
const trainersOnly = hardOnly || process.argv.includes("--trainers");
const old = trainersOnly ? await import("../src/data/gymtune.js") : null;
const out = {};
const t0 = Date.now();
/* WHERE EACH OPPONENT STANDS, which the engine reads to enforce the order
   (src/game/league.js) without the rosters: its region, its role and its place
   in that role. Derived, never solved, so `--trainers` rewrites them too. */
const where = (r) => ({ region: r.region.id, kind: r.role, k: r.k });
for (const [k, r] of rungs.entries()) {
  if (trainersOnly) {
    const { T, cap, top, target, win } = old.GYMTUNE[r.o.id];
    out[r.o.id] = { ...where(r), T, cap, top, target, win };
    continue;
  }
  const s = solve(r, share, { n: 200, seed: 5 });
  out[r.o.id] = { ...where(r), T: r.T, cap: r.cap, top: s.top, target: r.target, win: s.win };   // s.win is on the RECORD
  const off = Math.round((s.win - r.target) * 100);
  process.stdout.write(`\r  ${k + 1}/${rungs.length} ${r.region.name} ${r.o.name}`.padEnd(48));
  if (Math.abs(off) > 10) console.log(`\n    ${r.o.name}: cap ${r.cap}, ace ${s.top}, won ${Math.round(s.win * 100)}% for ${Math.round(r.target * 100)}%`);
}
if (!trainersOnly) console.log(`\n  solved ${rungs.length} in ${Math.round((Date.now() - t0) / 1000)}s`);

const trainers = {};
let lowered = 0;
for (const r of rungs.filter((x) => x.role === "leader")) {
  if (hardOnly) { for (const t of r.o.trainers) trainers[t.id] = old.TRAINERTUNE[t.id]; continue; }
  for (const t of r.o.trainers) {
    const rung = { ...r, o: t, role: "trainer", type: r.o.type, leader: r.o, leaderTop: out[r.o.id].top };
    const s = solveTrainer(rung, share);
    trainers[t.id] = { gym: r.o.id, top: s.top, win: s.win };
    if (s.top < trainerTop(t, r.o, out[r.o.id].top)) lowered++;
  }
}
console.log(`  ${Object.keys(trainers).length} gym trainers, ${lowered} lowered to clear the floor`);

const p = prices(rungs);
rungs.forEach((r, k) => { out[r.o.id].prize = p.prize[k]; });

/* HARD MODE: every capped opponent again, solved on its training alone. */
const hard = {};
const hp = hardPrices(rungs);
const short = [];
const h0 = Date.now();
for (const [k, r] of hardRungs().entries()) {
  const s = solveHard(r, share);
  hard[r.o.id] = { region: r.region.id, kind: r.kind, k: r.k, top: s.top, win: s.win, gift: signature(r.base) };
  process.stdout.write(`\r  hard ${k + 1}/${rungs.length} ${r.region.name} ${r.base.name}`.padEnd(48));
  if (s.win > HARD_TARGET + 0.1) short.push(`${r.region.name} ${r.base.name} ${Math.round(s.win * 100)}%`);
}
console.log(`\n  hard mode solved in ${Math.round((Date.now() - h0) / 1000)}s; ${short.length} stay above ` +
  `${HARD_TARGET * 100}% at the most training: ${short.join(", ")}`);

const rows = (o) => Object.entries(o).map(([id, v]) => `  ${JSON.stringify(id)}: ${JSON.stringify(v)}`).join(",\n");
writeFileSync(new URL("../src/data/gymtune.js", import.meta.url),
  "// Generated by tools/tune-gyms.mjs - do not edit by hand. docs/battles.md, *Difficulty*.\n" +
  `export const SHARE = ${share};\n` +
  `export const GYM_PRIZE = ${p.gymPrize};\n` +
  `export const REMATCH_STEPS = ${p.rematchSteps};\n` +
  `export const GYMTUNE = {\n${rows(out)}\n};\n` +
  `export const TRAINERTUNE = {\n${rows(trainers)}\n};\n` +
  `export const HARD_PRIZE = ${hp.prize};\n` +
  `export const HARD_FEE = ${hp.fee};\n` +
  `export const HARDTUNE = {\n${rows(hard)}\n};\n`);
console.log(`  gymPrize ${p.gymPrize} encounters, one-off prizes ¥${p.oneOff} of a Lv 75 game's ¥${Math.round(p.lifetime)}, ` +
  `rematch clock ${p.rematchSteps} steps`);
